server:
  port: 8011

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: 342800
      url: jdbc:mysql://localhost:3306/db_learning?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      filters: stat,wall,log4j2
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/api/ext/druid/*"
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
  aop:
    auto: true #启动aop配置

logging:
  config: classpath:log4j2.xml
  #mybatis-plus配置控制台打印完整带参数SQL语句
  level:
    com.example.demo1210.mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:/mapper/**/*.xml